/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author cookiebot
 */
public class HitboxEditor extends javax.swing.JFrame {

    Module[] modules;
    int num_modules;
    int num_frames;
    int num_hitboxes;
    /**
     * Creates new form HitboxEditor
     */
    public HitboxEditor() {
        modules = Modules.getModules();
        initComponents();
        module.setModel(new SpinnerNumberModel(1, 1, modules.length, 1));
        changeModule((Integer)(module.getValue())-1);
    }
    
    public void changeModule(int newModule){
        frame.setModel(new SpinnerNumberModel(0, 0, modules[newModule].animation.length, 1));
        hitbox.setModel(new SpinnerNumberModel(1, 1, modules[newModule].hitbox.resting.length, 1));
        if(modules[newModule].hitbox.resting.length == 0 || modules[newModule].hitbox.resting[0].radius == 0){
            SpinnerNumberModel m = new SpinnerNumberModel(0,0,0,1);
            size.setModel(m); size.setEnabled(false);
            x.setModel(m); x.setEnabled(false);
            y.setModel(m); y.setEnabled(false);
            type.setModel(m); type.setEnabled(false);
            intensity.setModel(m); intensity.setEnabled(false);
        }
        else {
            size.setModel(new SpinnerNumberModel(1, modules[newModule].hitbox.resting[0].radius, 50, 1));
            x.setModel(new SpinnerNumberModel(0, modules[newModule].hitbox.resting[0].x, 80, 1));
            y.setModel(new SpinnerNumberModel(0, modules[newModule].hitbox.resting[0].y, 80, 1));
            type.setModel(new SpinnerNumberModel(1, modules[newModule].hitbox.resting[0].type, 10, 1));
            intensity.setModel(new SpinnerNumberModel(1, modules[newModule].hitbox.resting[0].intensity, 100, 1));
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        module = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frame = new javax.swing.JSpinner();
        hitbox = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        size = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        x = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        y = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        type = new javax.swing.JSpinner();
        intensity = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        addHitbox = new javax.swing.JButton();
        deleteHitbox = new javax.swing.JButton();
        save = new javax.swing.JButton();
        revert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        module.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moduleStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yrsa", 0, 36)); // NOI18N
        jLabel1.setText("Hitbox Editor");

        jLabel2.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel2.setText("Module");

        jLabel3.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel3.setText("Frame");

        frame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frameStateChanged(evt);
            }
        });

        hitbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hitboxStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel4.setText("Hitbox");

        jLabel5.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel5.setText("Size");

        jLabel6.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel6.setText("x");

        jLabel7.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel7.setText("y");

        jLabel8.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel8.setText("Type");

        jLabel9.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel9.setText("Intensity");

        addHitbox.setText("Add Hitbox");
        addHitbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHitboxActionPerformed(evt);
            }
        });

        deleteHitbox.setText("Remove Hitbox");

        save.setText("Save All");

        revert.setText("Revert All");
        revert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hitbox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intensity, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addHitbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteHitbox)
                                .addGap(44, 44, 44)
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revert)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(frame)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hitbox)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(size)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(x)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(y)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(type)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHitbox)
                    .addComponent(deleteHitbox)
                    .addComponent(save)
                    .addComponent(revert))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addHitboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHitboxActionPerformed
        HitboxPoint[] currentHitboxes;
        if((int)frame.getValue() == 0)
            currentHitboxes = modules[(int)module.getValue()-1].hitbox.resting;
        else
            currentHitboxes = modules[(int)module.getValue()-1].hitbox.animation[(int)frame.getValue()-1];
        HitboxPoint[] newHitboxes = new HitboxPoint[currentHitboxes.length+1];
        for(int i = 0; i < currentHitboxes.length; i ++){
            newHitboxes[i] = currentHitboxes[i];
        }
        newHitboxes[newHitboxes.length-1] = new HitboxPoint(40,40,10,1,100);
        
        if((int)frame.getValue() == 0)
            modules[(int)module.getValue()-1].hitbox.resting = newHitboxes;
        else
            modules[(int)module.getValue()-1].hitbox.animation[(int)frame.getValue()-1] = newHitboxes;
        hitbox.setValue(newHitboxes.length+1);
    }//GEN-LAST:event_addHitboxActionPerformed

    private void revertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revertActionPerformed

    private void moduleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moduleStateChanged
        changeModule((Integer)(module.getValue())-1);
    }//GEN-LAST:event_moduleStateChanged

    private void frameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frameStateChanged
        int moduleNum = (int)module.getValue()-1;
        HitboxPoint[] hitboxframe;
        if(moduleNum == 0)hitboxframe = modules[moduleNum].hitbox.resting;
        else hitboxframe = modules[moduleNum].hitbox.animation[moduleNum-1];
        
        hitbox.setModel(new SpinnerNumberModel(1, 1, hitboxframe.length, 1));
        if(hitboxframe.length == 0){
            SpinnerNumberModel m = new SpinnerNumberModel(0,0,0,1);
            size.setModel(m); size.setEnabled(false);
            x.setModel(m); x.setEnabled(false);
            y.setModel(m); y.setEnabled(false);
            type.setModel(m); type.setEnabled(false);
            intensity.setModel(m); intensity.setEnabled(false);
        }
        else {
            size.setModel(new SpinnerNumberModel(1, hitboxframe[0].radius, 50, 1));
            x.setModel(new SpinnerNumberModel(0, hitboxframe[0].x, 80, 1));
            y.setModel(new SpinnerNumberModel(0, hitboxframe[0].y, 80, 1));
            type.setModel(new SpinnerNumberModel(1, hitboxframe[0].type, 10, 1));
            intensity.setModel(new SpinnerNumberModel(1, hitboxframe[0].intensity, 100, 1));
        }
    }//GEN-LAST:event_frameStateChanged

    private void hitboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hitboxStateChanged
        int moduleNum = (int)module.getValue()-1;
        HitboxPoint[] hitboxframe;
        if(moduleNum == 0)hitboxframe = modules[moduleNum].hitbox.resting;
        else hitboxframe = modules[moduleNum].hitbox.animation[moduleNum-1];
        
        int hitboxNum = (int)hitbox.getValue()-1;
        
        if(hitboxframe.length == 0){
            SpinnerNumberModel m = new SpinnerNumberModel(0,0,0,1);
            size.setModel(m); size.setEnabled(false);
            x.setModel(m); x.setEnabled(false);
            y.setModel(m); y.setEnabled(false);
            type.setModel(m); type.setEnabled(false);
            intensity.setModel(m); intensity.setEnabled(false);
        }
        else {
            size.setModel(new SpinnerNumberModel(1, hitboxframe[hitboxNum].radius, 50, 1));
            x.setModel(new SpinnerNumberModel(0, hitboxframe[hitboxNum].x, 80, 1));
            y.setModel(new SpinnerNumberModel(0, hitboxframe[hitboxNum].y, 80, 1));
            type.setModel(new SpinnerNumberModel(1, hitboxframe[hitboxNum].type, 10, 1));
            intensity.setModel(new SpinnerNumberModel(1, hitboxframe[hitboxNum].intensity, 100, 1));
        }
    }//GEN-LAST:event_hitboxStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitboxEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitboxEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitboxEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitboxEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitboxEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHitbox;
    private javax.swing.JButton deleteHitbox;
    private javax.swing.JSpinner frame;
    private javax.swing.JSpinner hitbox;
    private javax.swing.JSpinner intensity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner module;
    private javax.swing.JButton revert;
    private javax.swing.JButton save;
    private javax.swing.JSpinner size;
    private javax.swing.JSpinner type;
    private javax.swing.JSpinner x;
    private javax.swing.JSpinner y;
    // End of variables declaration//GEN-END:variables
}
